    	"collector_title" => "Simulador OGame V7.5: producción del Recolector",
        "collector_conso" => "Consumo",
        "collector_simulate_button" => "Simular",
        "collector_surcharge" => "Taladrador overload",
        "collector_only" => "Sólo recolector",
        "collector_class" => "Clase recolector",
        "collector_class_bonus" => "<i>Bono de Taladrador</i> - <b>Comprobar si recolecta</b>",
        "collector_geologue" => "Geólogo habilitado",
        "collector_geologue_bonus" => "<i>+10% de energía</i> - <b>Sólo recolector</b>",
        "collector_nb_foreuse_utiles" => "Taladradores usados",
        "collector_bonus_max" => "Bonificación máxima de producción",
        "collector_energie_foreuses" => "Energía necesaria para los taladradores",
        "collector_ernergie_totale" => "Energía TOTAL necesaria (planeta)",
        "collector_somme_mines" => "suma de minas",
        "collector_nrj_cef_title" => "Combinaciones de Energía / Reactor de Fusión",
        "collector_nrj_cef" => "Nivel de energía / Nivel del reactor de fusión",
        "collector_pub" => '<span class="status_positif">¿Algunos asaltantes a tu alrededor?<br><br>Comparte el enlace de PTRE en el juego o mediante Discord:<br><br><input onClick="this.select();" value="https://ptre.chez.gg/?page=splash&lang=en"></input></span>',
        "collector_cef_prod" => "producción CEF",