    	"search_simple_search_title" => "Simple search",
    	"search_advanced_search_title" => "Advanced search",
    	"search_simple_search_intro" => "Do a research depending on nickname / alias / name:",
    	"search_simple_search_ex" => 'For instance, if you type "fou", you will get all results related to Lefou or Fougasse.',
        "search_advanced_search_intro" => "Add some criteria to do a BDD search. You need to <b>modifiy at least one criteria</b> to apply a research. You dont need to modify all parameters.",
        "search_min_max_fleet_pts_com" => "You may leave it empty",
        "search_min_max_def_pts_com" => "You may leave it empty",
        "search_error" => "No criteria... You need to modity at leat one criteria.",