    	"search_simple_search_title" => "Búsqueda sencilla",
    	"search_advanced_search_title" => "Búsqueda Avanzada",
    	"search_simple_search_intro" => "Haz una investigación dependiendo del apodo/alias/nombre:",
        "search_simple_search_ex" => 'Por ejemplo, si escribe "fou", obtendrá todos los resultados relacionados con Lefou o Fougasse.',
        "search_advanced_search_intro" => "Agregue algunos criterios para realizar una búsqueda BDD. Es necesario <b>modificar al menos un criterio</b> para aplicar una investigación. No es necesario modificar todos los parámetros.",
        "search_min_max_fleet_pts_com" => "Puedes dejarlo vacío",
        "search_min_max_def_pts_com" => "Puedes dejarlo vacío",
        "search_error" => "Sin criterios... Es necesario modificar al menos un criterio.",