"ptre_slogan" => 'Base de datos de informes de espías atemporales,<br>Bot e interfaz de Discord, integración con <span class="status_positif">OGLight</span>, <span class="status_negatif">Infinity</span>, <span class="status_warning">EasyPTRE para AGR</span>,<br>Perfil de actividad dentro del juego, actualizaciones de galaxias para los navegadores de los compañeros de equipo...',
    	"test" => "prueba", 
        "ptre_pres_link_label" => "PRESENTACIÓN DE PTRE",
        "graveyard_link_label" => "Panel de control del cementerio",
        "news" => '<a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE para AGR</a><br><a href="/?page=galaxy_event_explorer">EXPLORADOR DE EVENTOS GALACTICOS</a><br><a href="/?page=position_8_finder">BUSCADOR DE POSICIÓN 8</a><br><span class="status_positif">Galaxy compartió IG<br>tabla de actividades de IG</b>',
        "team_info" => "Conectado a ",
        "team_info_tooltip" => "Podrás acceder a Informes de Espionaje privados (y también públicos)",
        "team_link" => "Gestión de equipos",
        "admin_link" => "Administration",
        "admin_info_tooltip" => 'Gestiona la configuración de tu equipo',
        "player_list_link" => "Lista de jugadores y estado",
        "archives_link" => "Gestión de Archivos e Informes",
        "team_no_logged_warning" => 'No estas conectado a tu equipo',
        "team_no_logged_link" => "Conectar | Crear equipo",
        "alias_search_error" => '<b>ERROR: La búsqueda debe contener al menos 3 letras.</b><br><a href="/?page=search">hacer otra busqueda</a>',
        "ship_202" => "Nave pequeña de carga",
        "ship_203" => "Nave grande de carga",
        "ship_204" => "Cazador ligero",
        "ship_205" => "Cazador pesado",
        "ship_206" => "Crucero",
        "ship_207" => "Nave de batalla",
        "ship_208" => "Colonizador",
        "ship_209" => "Reciclador",
        "ship_210" => "Sonda de espionaje",
        "ship_211" => "Bombardero",
        "ship_212" => "Satélite Solar",
        "ship_213" => "Destructor",
        "ship_214" => "Estrella de la muerte",
        "ship_215" => "Acorazado",
        "ship_217" => "Taladrador",
        "ship_218" => "Segador",
        "ship_219" => "Explorador",
        "research_106" => "Tecnología de espionaje",
        "research_108" => "Tecnología de computación",
        "research_109" => "Tecnología militar",
        "research_110" => "Tecnología de defensa",
        "research_111" => "Tecnología de blindaje",
        "research_113" => "Tecnología de energia",
        "research_114" => "Tecnología de hiperespacio",
        "research_115" => "Motor de combustión",
        "research_117" => "Motor de impulso",
        "research_118" => "Propulsor hiperespacial",
        "research_120" => "Tecnología láser",
        "research_121" => "Technología iónica",
        "research_122" => "Technología de plasma",
        "research_123" => "Red de investigación intergaláctica",
        "research_124" => "Astrofísica",
        "research_199" => "Tecnología de gravitón",
        "def_401" => "Lanzamisiles",
        "def_402" => "Láser pequeño",
        "def_403" => "Láser grande",
        "def_404" => "Cañón gauss",
        "def_405" => "Cañón iónico",
        "def_406" => "Cañón de plasma",
        "def_407" => "Cúpula pequeña de protección",
        "def_408" => "Cúpula grande de protección",
        "def_502" => "Misiles antibalísticos",
        "def_503" => "Misil interplanetario",
        "building_1" => "Mina de metal",
        "building_2" => "Mina de cristal",
        "building_3" => "Sintetizador de deuterio",
        "building_4" => "Planta de energía solar",
        "building_12" => "Planta de fusión",
        "building_14" => "Fábrica de robots",
        "building_15" => "Fábrica de nanobots",
        "building_21" => "Hangar",
        "building_22" => "Almacén de metal",
        "building_23" => "Almacén de cristal",
        "building_24" => "Contenedor de deuterio",
        "building_31" => "Laboratorio de investigación",
        "building_33" => "Terraformer",
        "building_34" => "Deposito de la alianza",
        "building_36" => "Astillero orbital",
        "building_41" => "Base Lunar",
        "building_42" => "Sensor Phalanx",
        "building_43" => "Salto Cúantico",
        "building_44" => "Silo",
        "footer_status_1" => "Este mes: ",
        "footer_status_re" => " nuevos informes de espionaje, que incluyen ",
        "footer_status_re_ogl" => " desde OGLight, ",
        "footer_status_teams_actives" => " Equipos activos en la web, ",
        "footer_status_discord" => " servidores de Discord activos, ",
        "footer_status_nb_acti_pushed" => " Impulsadas las actividades de IG, ",
        "footer_status_nb_grap" => " avtividades graficas desplegadas",
        "public_tooltip" => "Este informe de espionaje es público.",
        "private_tooltip" => "Solo los miembros del equipo pueden ver este informe.",
        "moon" => "Luna",
        "planet" => "Planeta",
        "fleet_points" => "puntos de flota",
        "def_points" => "puntos de defensa",
        "invisible_fleet" => "Flota invisible",
        "invisible_def" => "Defensa invisible",
        "no_tech" => "Sin tecnología",
        "tech_here" => "Tecnología disponible",
        "tech_tooltip" => "Este informe contiene la tecnología del jugador.",
        "ships" => "Naves",
        "resources" => "recursos",
        "report_tooltip" => "Haga clic aquí para desactivar este informe. Se eliminará en una semana.",
        "report_link" => "Desactivar este informe",
        "report_date" => "Este informe ha sido reportado desde ",
        "unreport_tooltip" => "Haga clic aquí para eliminar el informe",
        "unreport_link" => "Denunciar",
        "archive_link" => "Archivar este informe",
        "archive_tooltip" => "Un informe archivado no se eliminará",
        "report_public_error" => "No puedes denunciar un informe de espionaje público",
        "report_public_error_tooltip" => "Sólo se pueden reportar informes de espionaje privados",
        "archive_date" => "Este informe está archivado desde ",
        "unarchive_link" => "Desarchivar este informe",
        "spy_report" => "Informe de espionaje",
        "public" => "público",
        "private" => "privado",
        "fleet_evolution_disabled" => "No hay informe previo para comparar.",
        "alias_tooltip" => "Puede modificar este alias. Te ayudará a reagrupar varios informes de espionaje de un jugador en caso de que haya cambiado su nombre de IG.",
        "alias_no_edit" => "No puedes editar un alias de informe de espionaje público",
        "ag_sim_ok" => "SR reciente: Simular en Trashsim",       
        "ag_sim_too_old" => "Antiguo SR, Trashsim no puede recuperarlo directamente",       
        "ag_sim_link" => "Simulación de planos",       
        "ag_sim_com" => "Planificar un ataque multijugador:",       
        "ag_sim_att" => "Agregar jugador al ataque",       
        "ag_sim_def" => "Añadir jugador a la defensa",       
        "sr_already_reported" => "Este informe ya ha sido reportado.",
        "sr_already_archived" => "Este informe ya ha sido archivado.",
        "player" => "Jugador",
        "user_techs_missing" => "Añade tus technos para este universo",
        "information_title" => "Informaciones",
        "resource_title" => "Recursos",
        "evolution_title" => "Evolución de la flota",
        "fleet_title" => "Flota",
        "defense_title" => "Defensas",
        "building_title" => "Edificios",
        "technology_title" => "Tecnología",
        "reporting_title" => "Informes",
        "fleet_missing" => "No hay información de flota disponible",
        "def_missing" => "No hay información de defensa disponible",
        "building_missing" => "No hay información del edificio disponible",
        "tech_missing" => "No hay información tecnológica disponible.",
        "result_label" => "Resultado para",
        "no_result_label" => "No se han encontrado resultados. ¿Estás seguro de estar conectado al equipo/universo correcto?",
        "alias_cant_update_pub_sr" => "Cant update public spy report alias",
        "alias_cant_update_same" => "Nada que hacer (mismo valor)",
        "alias_update_ok" => "Alias ​​actualizado. Todos los informes: ",
        "alias_update_ko" => "No puedo actualizar el alias: ",
        "reporting_ok" => 'Se ha informado de un informe de espionaje.<br>Se eliminará en una semana..<br><a href="/?page=reported">Verifique todos los informes de espionaje reportados</a>.',
        "reporting_ko" => "Error: No puedo informar el informe de espionaje",
        "reporting_unreport_ok" => "El informe de espionaje no ha sido reportado.",
        "reporting_unreport_ko" => "Error: No puedo anular el informe de espionaje",
        "reporting_archive_ok" => "El informe de espionaje había sido archivado.",
        "reporting_archive_ko" => "Error: No puedo archivar el informe de espionaje",
        "reporting_archive_ko_admin" => "Error: Sólo un administrador puede archivar un informe de espionaje",
        "reporting_unarchive_ok" => "El informe de espionaje ha sido desarchivado.",
        "reporting_unarchive_ko" => "Error: No puedo desarchivar el informe de espionaje",
        "reporting_unarchive_ko_admin" => "Error: Sólo un administrador del equipo puede desarchivar un informe de espionaje",
        "discord_private_sr_error" => 'No tienes permiso para mostrar este informe de espionaje..<br><br><span class="status_positif"><a href="/?page=team">Conectar</a> con llave de equipo.<br>Si no tienes uno, solicítalo a un administrador de tu equipo.<br><br>Agregar una clave de equipo: <form style="display: inline-block;" method="post" action="scripts/login.php"><input type="text" name="team_key_login" id="team_key_login" size="15" placeholder="TM-XXXX / AD-XXXX" required></input><input type="submit" value="Connect"></form></span>',
        "raw_sr_error_logged" => 'No tienes permiso para mostrar este informe de espionaje.<br><br><span class="status_positif">Ya estás conectado a un equipo.</span><br><br>',
        "raw_sr_error_logged2" => '<span class="status_negatif">Ningún equipo coincidente. Solicite la clave del equipo y agréguela: </span><br><form method="post" action="scripts/team_add.php"><input name="team_key_login" id="team_key_login" size="20" placeholder="TM-XXXX-XXXX-XXXX-XXXX" required></input><input type="submit" value="Add a Team"></form><br><br>',
        "raw_sr_error_logged3" => '<span class="status_positif">Puede administrar sus equipos a través del <a href="/?page=team#multi-team">Gestión multiequipo</a> menú.</span>',
        "discord_private_sr_error_swap_display" => 'Mostrar informe conectándose al equipo ',
        "discord_private_sr_error_swap" => 'Conéctate al equipo ',
        "discord_cant_find_sr" => "No puedo encontrar este informe de espionaje",
        "alias_link_before" => "",
        "alias_link_after" => "'perfil",
        "alias_link_tooltip" => "Alias ​​PTRE del jugador",
        "expedetector_link_before" => "",
        "expedetector_link_after" => "Perfil del expedetector",
        "team_no_discord_server" => "No tienes ningún servidor de Discord asociado a tu equipo. !",
        "team_no_discord_server_not_admin" => "Pídale a un administrador del equipo que lo haga (el creador del equipo).",
        "team_key_swaped" => "Conectado al equipo ",
        "team_key_added" => "Se agregó la clave del equipo. ¡Bienvenido!",
        "team_key_added_suite" => "<br><br>Universo seleccionado: ",
        "team_key_added_no_uni" => "<br><br>Ningún universo seleccionado",
        "team_key_added_home_link" => "Mostrar últimos informes",
        "team_creation_failed_size" => "No puedo crear este equipo (min 2 carac)",
        "team_creation_already_exists" => "No puedo crear este equipo: el nombre ya se usó",
        "team_creation_already_created" => "No puedo crear un equipo, ya creaste 5 equipos. Solicite la creación de equipos personalizados en Discord.",
        "team_creation_ok" => "¡Equipo creado!<br><br>No pierdas tu CLAVE DE ADMIN, cópiala en un documento: ",
        "multi_team_key_already_exists" => "La clave ya existe",
        "multi_team_key_key_added" => "La clave ha sido agregada",
        "multi_team_max_nb_keys" => "No puedo agregar clave: no queda ranura (5 claves como máximo)",
        "easy_ag_simulator_no_sim" => 'Error: No se inició ninguna simulación.<br><a href="/?page=easy_ag_simulator">Abra el simulador Easy ACS antes</a>.',
        "key_removed" => "Clave eliminada",
        "search_error_min" => "ERROR: la investigación debe contener al menos 3 letras/números",
        "main_title" => "Últimos 10 informes (flotas)",
        "main_intro_1" => ' informes de espionaje para este universo',
        "main_intro_2" => ' informes de espionaje privados',
        "player_list_color_1" => "< 1 semana",
        "player_list_color_2" => "< 1 mes",
        "player_list_color_3" => "> 1 mes",
        "player_acti_color_1" => "< 1 hora",
        "player_acti_color_2" => "< 1 día",
        "player_acti_color_3" => "> 1 día",
        "display_report" => "Mostrar informe",
        "spy_report_added" => "¡Informe espía agregado!",
        "spy_report_added_error" => "No puedo obtener el informe. Etiqueta de error: ",
        "spy_report_added_exists" => "El informe ya existe para este equipo.",
        "class_label" => "Clase: ",
        "collector" => "Recolector",
        "general" => "General",
        "discoverer" => "Descubridor",
        "no_class" => "Sin clase",
        "collector_mini" => "[R]",
        "general_mini" => "[G]",
        "discoverer_mini" => "[D]",
        "no_class_mini" => "[?]",
        "activity_label" => "Actividad: ",
        "profile_label" => "Perfil PTRE",
        "spy_label" => "Espiar: ",
        "activity_raw_data" => "Tabla de actividades dentro del juego",
        "activity_graph_label" => "Gráfico de actividad dentro del juego",
        "last_gala_event" => "Últimos eventos de galaxias",
        "last_spy" => "último espía",
         "activity_graph_intro" => 'Para enviar datos al gráfico de actividad, necesita instalar <a href="https://board.fr.ogame.gameforge.com/index.php?thread/722955-oglight/&postID=11950870#post11950870" target="_blank">OGLight</a> y agregue su clave de equipo a la configuración de OGL.<br>Luego, debe fijar el objetivo y comprobar las posiciones de todos los objetivos a través del menú fijado.<br>',
        "activity_graph_intro2" => '<b>Aquí puede ver los últimos datos ingresados ​​en orden.<br>para comprobar si el impulso de actividad está funcionando.</b><br><br><table><tr><td align="right"><span class="status_positif">(COA)</span> : </td><td>Indica una actividad agregada por un Equipo de tu Coalición.</td></tr><tr><td align="right"><span class="status_warning">(espía)</span> : </td><td>El jugador estaba espiando actualmente.</td></tr></table><br>',
        "activity_graph_intro3" => 'Seleccione opciones de visualización.<br><br>',
        "activity_graph_not_available" => 'No hay datos suficientes para crear un gráfico de actividad.<br><br>Necesitas instalar <a href="https://board.fr.ogame.gameforge.com/index.php?thread/722955-oglight/&postID=11950870#post11950870" target="_blank">OGLight</a>, Fije el objetivo y verifique todas sus posiciones para actualizar las actividades.',
        "activity_oglight_data_not_available" => 'No hay suficientes datos de OGLight. Necesitas instalar <a href="https://board.fr.ogame.gameforge.com/index.php?thread/722955-oglight/&postID=11950870#post11950870" target="_blank">OGLight</a>.',
        "activity_graph_not_connected" => 'Necesitas estar conectado para ver gráficos de actividad.',
        "activity_recent_galaxy_update_warning" => 'Los datos públicos de Galaxy se actualizaron recientemente, por lo que no hay mucho que mostrar en este momento.<br>Come back tomorrow.',
        "migration_add_sr" => "SR agregado a la lista de migración: ",
        "migration_add_failed" => 'No puedo agregar este SR a la lista de migración: migre primero los que ya están seleccionados',
        "migration_title" => "Migración SR",
        "migration_link" => "Migrar este SR a otro universo",
        "migration_available" => "Universos disponibles: ",
        "migration_text" => 'Puede seleccionar hasta 10 informes para migrar (al mismo tiempo) al mismo universo.<br>Debes tener al menos un informe de espionaje adjunto al universo objetivo (para permitir el objetivo)',
        "sr_migrated_label" => "SR migrado",
        "player_profil_not_found" => '<span class="status_negatif large_text">No puedo encontrar un informe de espionaje para este jugador.</span><br><br>',
        "player_profil_not_found_logged" => '¿Estás seguro de estar conectado al equipo adecuado?:<br><br>',
        "player_profil_not_found_not_logged" => 'No estas conectado a un equipo.<br><br><a href="/?page=team">Por favor conectate</a> mediante el uso de una clave de equipo.</a>',
        "player_profil_not_found_swap_team" => 'Cambiar al equipo ',
        "carto_player_not_found" => 'No puedo encontrar esta API de reproductor. ¿Es posible que el jugador ya no exista?',
        "report_player_into" => 'Si estás realmente seguro, puedes eliminar todos los informes de espionaje de este jugador: ',
        "report_player_tooltip" => "Precaución",
        "report_player_link" => "Informa y elimina todos sus informes de espionaje.",
        "report_all_player_ok" => "El jugador ha sido reportado.",
        "report_universe" => "SR informó: ",
        "cartography_title" => "Cartografía",
        "stats_status_re" => "<b>Informes totales de espionaje</b>",
        "stats_status_re_ogl" => '<b>Informes de espionaje</b><br>Desde Discord<br><span class="status_positif">Desde OGLight</span><br><span class="status_negatif">Desde Infinity</span><br><span class="status_warning">Desde <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a> para AGR</span><br>Desde la Web',
        "stats_status_teams_actives" => "<b>Equipos activos - Sitio web</b>",
        "stats_status_discord" => "<b>Equipos activos - Discord</b>",
        "stats_status_nb_acti_pushed" => '<b>Actividades dentro del juego</b><br><span class="status_positif">Desde OGLight</span><br><span class="status_negatif">Desde Infinity</span><br><span class="status_warning">Desde EasyPTRE</span>',
        "stats_status_nb_ogl_requests" => '<b>Solicitudes de perfil de IG</b><br><span class="status_positif">Desde OGLight</span><br><span class="status_negatif">Desde Infinity</span>',
        "stats_status_nb_grap" => "<b>Se muestra el gráfico de actividad</b><br><i>Sitio web, sólo</i>",
        "stats_status_nb_planets" => "<b>Los planetas importados cuentan</b>",
        "more_statistics" => "Más estadísticas",
        "ptre_statistics" => "estadísticas de PTRE",
        "easy_ag_simulator_intro" => "<b>¿Cómo funciona?</b><br><br>
        <ul>
            <li>Requisito: <b>Todas y cada una de las flotas que necesitas en el ACS deben añadirse a PTRE</b>. Si no: inicie sesión y agregue los informes de espías que faltan. (Recordatorio: el informe de espionaje agregado <b>sin estar conectado a un equipo será público</b>.)</li>
            <li>Haga clic en <b>\"Añadir una flota\"</b> y navegue por el sitio web de PTRE para encontrar la flota que desea agregar: muestre el informe de espionaje</li>
            <li>Una vez en la página del informe de espionaje, seleccione <b>\"Agregar jugador al ataque\"</b> o <b>\"Añadir jugador a la defensa\"</b> para agregar el informe de espionaje a ACS</li>
            <li>Repita esto hasta que el ACS esté lleno (no es necesario completar los 10 espacios)</li>
            <li>¡Elija sus opciones debajo de la lista de flotas y valídelas!</li>
        </ul>",
        "easy_ag_simulator_no_tech" => "faltan tecnologías",
        "easy_ag_simulator_cdr" => "Porcentaje de escombros /!\\",
        "easy_ag_simulator_degrouper" => "Desagrupar flotas atacantes",
        "easy_ag_simulator_divide" => "Divide flotas y defensas por 10",
        "easy_ag_simulator_rip" => "Eliminar las Estrellas de la Muerte atacantes",
        "easy_ag_simulator_gt" => "Eliminar nave grande de carga ",
        "easy_ag_simulator_rec" => "Eliminar los recicladores atacantes",
        "easy_ag_simulator_probe" => "Eliminar sondas atacantes",
        "easy_ag_simulator_vc" => "Eliminar colonizadores atacantes",
        "easy_ag_simulator_sim_count" => "Las simulaciones cuentan",
        "easy_ag_simulator_attaquant" => "Atacantes",
        "easy_ag_simulator_defenseur" => "Defensores",
        "easy_ag_simulator_label" => 'Simulador de SCA sencillo',
        "public_spy_reports_label" => 'Informes públicos de espionaje',
        "main_title_public_sr" => 'Últimos informes públicos de espionaje',
        "main_title_public_sr_top" => 'Las 100 principales flotas públicas',
        "main_title_public_sr_add_sr" => 'Agregar un informe de espionaje público',
        "public_sr_add_sr_warning" => '<span class="status_negatif large_text">Agregar un informe de espionaje al siguiente formulario lo hará público, incluso si está conectado a su equipo PTRE.</span>',
        "public_sr_add_sr_warning_connected" => '<span class="large_text">Utilice el formulario en la esquina superior derecha para agregarlo a su equipo PTRE.</span>',
        "welcome_back_message" => 'Bienvenido de nuevo!<br><br>Puedes <a href="https://discord.gg/PQkSakJSPz" target="_blank">únete al Discord de PTRE</a> para estar al tanto de las últimas noticias,<br>proponer nuevas ideas, conseguir ayuda, etc...',
        "options_page_intro" => 'Añade tus investigaciones para enviarlas directamente al simulador. Debes completar todos y cada uno de los campos.<br><br>Puede definir una configuración por universo.',
        "options_page_tech_fight_title" => 'Investigación de combate',
        "options_page_tech_speed_title" => 'Investigación de propulsión',
        "options_page_tech_cargo_title" => 'Tecnología de hiperespacio',
        "options_page_speed" => 'Velocidad del universo',
        "options_page_speed_comment" => 'Establezca "1" como predeterminado.',
        "gee_presentation" => '<span class="medium_text">Galaxy Event Explorer mostrará la galaxia combinando 2 fuentes de datos:
                               <br>- Datos de la API pública actualizados una vez por semana (como en MMORPG)
                               <br><span class="status_posifit">- MÁS datos que tu equipo recopiló dentro del juego desde la última actualización pública de la API</span>
                               <br><br>Para recopilar datos del juego, debes instalar <a href="https://board.fr.ogame.gameforge.com/index.php?thread/722955-oglight/&postID=11950870#post11950870" target="_blank">OGLight</a></span>',
        "gee_punchline" => '<span class="medium_text">Verifica la galaxia actualizada como dentro del juego.</span>',
        "gee_public_user_warning" => 'Debes estar conectado a tu equipo para ver eventos en vivo dentro del juego.',
        "gee_pos_count" => ' nuevas posiciones fueron importadas por OGLight / Infinity desde la última actualización de la API pública',
        "p8_punchline" => '<span class="medium_text">¡Encuentra P8 gratis con un clic!</span>',
        "p8_presentation" => '<span class="medium_text">Utilice la siguiente tabla para seleccionar la posición que está buscando (¿P1, P8, P15?).<br>Luego, selecciona la posición para mostrar el sistema solar asociado.<br>Si estás conectado a tu equipo, se mostrarán los empujes de galaxias de OGLight dentro del juego.</span>',
        "messages_intro" => 'Cada mensaje será eliminado 24 horas después de ser leído.',
        "messages_user_comment" => 'Esos mensajes son para ti.',
        "messages_admin_comment" => 'Esos mensajes son para tu equipo.',
        "menu_link_discord" => "CONFIGURACION DISCORD",
        "menu_link_search" => "BUSQUEDA",
        "menu_link_options" => "OPCIONES",
        "no_universe_selected" => "Universo no seleccionado",
