<?php

    $lang_collector = ["collector_title" => "Simulateur OGame V7.5 : Production du Collecteur",
"collector_conso" => "Consommation",
"collector_simulate_button" => "Simuler",
"collector_surcharge" => "Surcharge des foreuses",
"collector_only" => "Collecteur uniquement",
"collector_class" => "Classe collecteur",
"collector_class_bonus" => "<i>Bonus foreuses</i> - <b>Cocher si Collecteur</b>",
"collector_geologue" => "Geologue activé",
"collector_geologue_bonus" => "<i>+10% d'énergie</i> - <b>Collecteur uniquement</b>",
"collector_nb_foreuse_utiles" => "Nombre de foreuses utiles",
"collector_bonus_max" => "Bonus maximal de production",
"collector_energie_foreuses" => "Energie nécessaire pour ces foreuses",
"collector_ernergie_totale" => "Energie TOTAL nécessaire (pour la planete)",
"collector_somme_mines" => "Somme des mines",
"collector_nrj_cef_title" => "Combinaisons possibles d'Energie / CEF",
"collector_nrj_cef" => "Energie level / CEF level",
"collector_pub" => '<span class="status_positif">Des raideurs parmis vos alliés ? <br><br>Pensez à partager le lien du PTRE IG et/ou via votre Discord :<br><br><input onClick="this.select();" value="https://ptre.chez.gg/?page=splash"></input></span>',
"collector_cef_prod" => "Production CEF"];