        "reported_description" => 'Tous les RE signalés n\'apparaissent plus sur le PTRE (excepté ici).<br><br><span class="status_negatif">Tous les RE dont le signalement date de plus d\'une semaine<br> seront automatiquement supprimés.</span><br><br><span class="status_warning">Un RE archivé reste conservé de façon permanante <br>mais n\'apparaitra plus dans les résultats (excepté ici).</span><br><br>Actuellement :<br>- ',
        "reported_reported_sr" => " rapports d'espionnages signalés",
        "reported_archived_sr" => " rapports d'espionnages archivés",
        "reported_reported_title" => "Vos rapports signalés",
        "reported_archived_title" => "Vos rapports archivés",