        "search_simple_search_title" => "Recherche simple",
        "search_advanced_search_title" => "Recherche avancée",
        "search_simple_search_intro" => "Effectuer une recherche en fonction du pseudo / alias / nom du joueur :",
        "search_simple_search_ex" => 'Ex : Si vous tapez "fou", vous trouver les RE liés à Lefou mais aussi à Fougasse.',
        "search_advanced_search_intro" => "Ajouter des critères afin d\'effectuer une recherche en base. Il faut <b>modifier au moins un critère</b> pour que la recherche soit valide. Il n\'est pas nécessaire de modifier tous les paramêtres.",
        "search_min_max_fleet_pts_com" => "Laisser vide pour ne pas limiter en fonction de la flotte",
        "search_min_max_def_pts_com" => "Laisser vide pour ne pas limiter en fonction de la défense",
        "search_error" => "Pas de critères... Veuillez modifier au moins un critère.",