<?php

    $lang = ["ptre_slogan" => 'Stockage de RE sans limite de temps,<br>interface et bot Discord, intégration dans <span class="status_positif">OGLight</span>, <span class="status_negatif">Infinity</span>, <span class="status_warning">EasyPTRE pour AGR/OGL/OGI</span>,<br>Profil d\'activité ingame, synchronisation de la galaxie entre alliés...',
"test" => "test",
"ptre_pres_link_label" => "PRESENTATION",
"graveyard_link_label" => "Monitoring du Cimetière",
"news" => '<a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE<br>Synchroniser vos Formes de Vies vers PTRE</a><br>EasyPTRE n\'est plus limité à AGR<br>Il fonctionne avec AGR, OGL et OGI<br><a href="/?page=lifeforms_researchs">Plus d\'infos ici</a>',
"team_info" => "Connecté à ",
"team_info_tooltip" => "Vous pouvez voir vos RE privés (ainsi que les RE publics)",
"team_link" => "MES EQUIPES",
"admin_link" => "ADMINISTRATION",
"admin_info_tooltip" => 'Gérer la configuration de votre Equipe',
"player_list_link" => "LISTE DES CIBLES",
"archives_link" => "ARCHIVES",
"team_no_logged_warning" => 'Vous n\'êtes pas connecté à votre Equipe',
"team_no_logged_link" => "SE CONNECTER | CREER EQUIPE",
"alias_search_error" => '<b>ERREUR : La recherche doit contenir au moins 3 caratères</b><br><a href="/?page=search">Effectuer une nouvelle recherche</a>',
"ship_202" => "Petit Transporteur",
"ship_203" => "Grand Transporteur",
"ship_204" => "Chasseur Léger",
"ship_205" => "Chasseur Lourd",
"ship_206" => "Croiseur",
"ship_207" => "Vaisseau de Bataille",
"ship_208" => "Vaisseau de Colonisation",
"ship_209" => "Recycleur",
"ship_210" => "Sonde d'Espionnage",
"ship_211" => "Bombardier",
"ship_212" => "Satellite Solaire",
"ship_213" => "Destructeur",
"ship_214" => "Étoile De La Mort",
"ship_215" => "Traqueur",
"ship_217" => "Foreuse",
"ship_218" => "Faucheur",
"ship_219" => "Eclaireur",
"research_106" => "Technologie Espionnage",
"research_108" => "Technologie Ordinateur",
"research_109" => "Technologie Armes",
"research_110" => "Technologie Bouclier",
"research_111" => "Protection des vaisseaux spatiaux",
"research_113" => "Technologie énergétique",
"research_114" => "Technologie hyperespace",
"research_115" => "Réacteur à combustion",
"research_117" => "Réacteur à impulsion",
"research_118" => "Propulsion hyperespace",
"research_120" => "Technologie Laser",
"research_121" => "Technologie à ions",
"research_122" => "Technologie Plasma",
"research_123" => "Réseau de recherche intergalactique",
"research_124" => "Astrophysique",
"research_199" => "Technologie Graviton",
"research_11201" => "Intergalactic Envoys",
"research_11202" => "High-Performance Extractors",
"research_11203" => "Fusion Drives",
"research_11204" => "Stealth Field Generator",
"research_11205" => "Orbital Den",
"research_11206" => "Research AI",
"research_11207" => "High-Performance Terraformer",
"research_11208" => "Enhanced Production Technologies",
"research_11209" => "Light Fighter Mk II",
"research_11210" => "Cruiser Mk II",
"research_11211" => "Improved Lab Technology",
"research_11212" => "Plasma Terraformer",
"research_11213" => "Low-Temperature Drives",
"research_11214" => "Bomber Mk II",
"research_11215" => "Destroyer Mk II",
"research_11216" => "Battlecruiser Mk II",
"research_11217" => "Robot Assistants",
"research_11218" => "Supercomputer",
"research_12201" => "Volcanic Batteries",
"research_12202" => "Acoustic Scanning",
"research_12203" => "High Energy Pump Systems",
"research_12204" => "Cargo Hold Expansion (Civilian Ships)",
"research_12205" => "Magma-Powered Production",
"research_12206" => "Geothermal Power Plants",
"research_12207" => "Depth Sounding",
"research_12208" => "Ion Crystal Enhancement (Heavy Fighter)",
"research_12209" => "Improved Stellarator",
"research_12210" => "Hardened Diamond Drill Heads",
"research_12211" => "Seismic Mining Technology",
"research_12212" => "Magma-Powered Pump Systems",
"research_12213" => "Ion Crystal Modules",
"research_12214" => "Optimised Silo Construction Method",
"research_12215" => "Diamond Energy Transmitter",
"research_12216" => "Obsidian Shield Reinforcement",
"research_12217" => "Rune Shields",
"research_12218" => "Rock’tal Collector Enhancement",
"research_13201" => "Catalyser Technology",
"research_13202" => "Plasma Drive",
"research_13203" => "Efficiency Module",
"research_13204" => "Depot AI",
"research_13205" => "General Overhaul (Light Fighter)",
"research_13206" => "Automated Transport Lines",
"research_13207" => "Improved Drone AI",
"research_13208" => "Experimental Recycling Technology",
"research_13209" => "General Overhaul (Cruiser)",
"research_13210" => "Slingshot Autopilot",
"research_13211" => "High-Temperature Superconductors",
"research_13212" => "General Overhaul (Battleship)",
"research_13213" => "Artificial Swarm Intelligence",
"research_13214" => "General Overhaul (Battlecruiser)",
"research_13215" => "General Overhaul (Bomber)",
"research_13216" => "General Overhaul (Destroyer)",
"research_13217" => "Experimental Weapons Technology",
"research_13218" => "Mechan General Enhancement",
"research_14201" => "Heat Recovery",
"research_14202" => "Sulphide Process",
"research_14203" => "Psionic Network",
"research_14204" => "Telekinetic Tractor Beam",
"research_14205" => "Enhanced Sensor Technology",
"research_14206" => "Neuromodal Compressor",
"research_14207" => "Neuro-Interface",
"research_14208" => "Interplanetary Analysis Network",
"research_14209" => "Overclocking (Heavy Fighter)",
"research_14210" => "Telekinetic Drive",
"research_14211" => "Sixth Sense",
"research_14212" => "Psychoharmoniser",
"research_14213" => "Efficient Swarm Intelligence",
"research_14214" => "Overclocking (Large Cargo)",
"research_14215" => "Gravitation Sensors",
"research_14216" => "Overclocking (Battleship)",
"research_14217" => "Psionic Shield Matrix",
"research_14218" => "Kaelesh Discoverer Enhancement",
"def_401" => "Lanceur de missiles",
"def_402" => "Artillerie laser légère",
"def_403" => "Artillerie laser lourde",
"def_404" => "Canon de Gauss",
"def_405" => "Artillerie à ions",
"def_406" => "Lanceur de plasma",
"def_407" => "Petit bouclier",
"def_408" => "Grand bouclier",
"def_502" => "Missile d'interception",
"def_503" => "Missile interplanétaire",
"building_1" => "Mine de métal",
"building_2" => "Mine de cristal",
"building_3" => "Synthétiseur de deutérium",
"building_4" => "Centrale Electrique Solaire",
"building_12" => "Centrale Electrique de Fusion",
"building_14" => "Usine de robots",
"building_15" => "Usine de nanites",
"building_21" => "Chantier spatial",
"building_22" => "Hangar de métal",
"building_23" => "Hangar de cristal",
"building_24" => "Réservoir de deutérium",
"building_31" => "Laboratoire de recherche",
"building_33" => "Terraformeur",
"building_34" => "Dépôt de ravitaillement",
"building_36" => "Dock spatial",
"building_41" => "Base lunaire",
"building_42" => "Phalange de Capteur",
"building_43" => "Porte de saut spatial",
"building_44" => "Silo de missiles",
"building_11101" => "Residental Sector",
"building_11102" => "Biosphere Farm",
"building_11103" => "Research Centre",
"building_11104" => "Academy of Sciences",
"building_11105" => "Neuro-Calibration Centre",
"building_11106" => "High Energy Smelting",
"building_11107" => "Food Silo",
"building_11108" => "Fusion-Powered Production",
"building_11109" => "Skyscraper",
"building_11110" => "Biotech Lab",
"building_11111" => "Metropolis",
"building_11112" => "Planetary Shield",
"building_12101" => "Meditation Enclave",
"building_12102" => "Crystal Farm",
"building_12103" => "Rune Technologium",
"building_12104" => "Rune Forge",
"building_12105" => "Oriktorium",
"building_12106" => "Magma Forge",
"building_12107" => "Disruption Chamber",
"building_12108" => "Megalith",
"building_12109" => "Crystal Refinery",
"building_12110" => "Deuterium Synthesiser",
"building_12111" => "Mineral Research Centre",
"building_12112" => "Advanced Recycling Plant",
"building_13101" => "Assembly Line",
"building_13102" => "Fusion Cell Factory",
"building_13103" => "Robotics Research Centre",
"building_13104" => "Update Network",
"building_13105" => "Quantum Computer Centre",
"building_13106" => "Automatised Assembly Centre",
"building_13107" => "-Performance Transformer",
"building_13108" => "Microchip Assembly Line",
"building_13109" => "Production Assembly Hall",
"building_13110" => "High-Performance Synthesiser",
"building_13111" => "Chip Mass Production",
"building_13112" => "Nano Repair Bots",
"building_14101" => "Sanctuary",
"building_14102" => "Antimatter Condenser",
"building_14103" => "Vortex Chamber",
"building_14104" => "Halls of Realisation",
"building_14105" => "Forum of Transcendence",
"building_14106" => "Antimatter Convector",
"building_14107" => "Cloning Laboratory",
"building_14108" => "Chrysalis Accelerator",
"building_14109" => "Bio Modifier",
"building_14110" => "Psionic Modulator",
"building_14111" => "Ship Manufacturing Hall",
"building_14112" => "Supra Refractor",
"footer_status_1" => "Ce mois : ",
"footer_status_re" => " nouveaux rapports d'espionnage, dont ",
"footer_status_re_ogl" => " depuis OGLight, ",
"footer_status_teams_actives" => " teams actives, ",
"footer_status_discord" => " serveurs Discord actifs, ",
"footer_status_nb_acti_pushed" => " activités IG ajoutées, ",
"footer_status_nb_grap" => " graphiques d'activités consultés, ",
"public_tooltip" => "Ce RE est visible de tous",
"private_tooltip" => "Seuls les membres de votre équipe peuvent voir ce RE",
"moon" => "Lune",
"planet" => "Planète",
"fleet_points" => "points flotte",
"def_points" => "points def",
"invisible_fleet" => "Flotte invisible",
"invisible_def" => "Def invisible",
"no_tech" => "Pas de tech",
"tech_here" => "Technos présentes",
"tech_tooltip" => "Ce RE contient les technologies du joueur",
"ships" => "vaisseaux",
"resources" => "ressources",
"report_tooltip" => "Cliquer ici pour déclarer ce RE comme obsolète. Celui-ci sera supprimé dans une semaine.",
"report_link" => "Signaler ce RE comme obsolète",
"report_date" => "Ce RE a été signalé le ",
"unreport_tooltip" => "Cliquer ici pour retirer le signalement",
"unreport_link" => "Retirer le signalement",
"archive_link" => "Archiver ce RE",
"archive_tooltip" => "Un RE archivé sera conservé et mit de côté.",
"report_public_error" => "Vous ne pouvez pas signaler un RE public.",
"report_public_error_tooltip" => "Seuls les RE privés peuvent être nettoyés",
"archive_date" => "Ce RE est archivé depuis le ",
"unarchive_link" => "Sortir des archives",
"spy_report" => "Rapport d'Espionnage",
"public" => "public",
"private" => "privé",
"fleet_evolution_disabled" => "Pas de RE précédent afin d'effectuer une comparaison de flotte",
"alias_tooltip" => "Vous pouvez modifier l'alias de ce RE avec le pseudo/surnom du joueur, par exemple. Cela facilitera vos recherches.",
"alias_no_edit" => "Impossible de modifier l'alias d'un RE public",
"ag_sim_ok" => "RE récent : Lancer une simulation sur Trashsim",
"ag_sim_too_old" => "RE trop vieux pour être directement récupéré par Trashsim",
"ag_sim_link" => "Préparer simulation",
"ag_sim_com" => "Préparer une AG :",
"ag_sim_att" => "Ajouter en tant qu'attaquant",
"ag_sim_def" => "Ajouter en tant que défenseur",
"sr_already_reported" => "Ce RE a déjà été signalé",
"sr_already_archived" => "Ce RE est déjà archivé",
"player" => "Joueur",
"user_techs_missing" => "Ajouter vos technologies pour cet univers",
"information_title" => "Informations",
"resource_title" => "Ressources",
"evolution_title" => "Comparatif avec le RE précédent",
"fleet_title" => "Flotte",
"defense_title" => "Défenses",
"building_title" => "Batiments",
"building_lf_title" => "Formes de Vie - Batiments",
"technology_title" => "Technologies",
"technology_lf_title" => "Formes de Vie - Technologies",
"technology_lf_ship_bonus_title" => "Formes de Vie - Bonus des Flottes",
"reporting_title" => "Signalement",
"fleet_missing" => "Impossible de voir la flotte",
"def_missing" => "Impossible de voir les defenses",
"building_missing" => "Impossible de voir les batiments",
"tech_missing" => "Impossible de voir les technologies",
"result_label" => "Résultats pour ",
"no_result_label" => 'Pas de résultat. Assurer-vous d\'être connecté à la bonne Equipe et d\'avoir sélectionné le bon univers.',
"alias_cant_update_pub_sr" => "Impossible de modifier un alias public",
"alias_cant_update_same" => "Rien à faire (l'alias vaut déjà cette valeur)",
"alias_update_ok" => "Mise à jour de l'alias. Tous les RE : ",
"alias_update_ko" => "Impossible de mettre à jour l'alias : ",
"reporting_ok" => 'Ce RE a été signalé.<br>Sans contre-ordre, il sera supprimé dans une semaine.<br><a href="/?page=reported">Voir tous les RE signalés.</a>.',
"reporting_ko" => "Erreur : Impossible de signaler ce RE",
"reporting_unreport_ok" => "Le signalement a été retiré",
"reporting_unreport_ko" => "Erreur : Impossible de retirer le signalement de ce RE",
"reporting_archive_ok" => "Le RE a été archivé",
"reporting_archive_ko" => "Erreur : Impossible d archiver ce RE",
"reporting_archive_ko_admin" => "Erreur : Il faut être admin de la team pour archiver un RE",
"reporting_unarchive_ok" => "Le RE a été désarchivé",
"reporting_unarchive_ko" => "Erreur : Impossible de désarchiver ce RE",
"reporting_unarchive_ko_admin" => "Erreur : Il faut être admin de la team pour désarchiver un RE",
"discord_private_sr_error" => 'Vous n\'êtes pas autorisé à accéder à ce rapport.<br><br><span class="status_positif"><a href="/?page=team">Veuiller vous connecter</a> via une clé d\'Equipe.<br>Si vous n\'en disposez pas, demandez là au créateur de votre Equipe.<br><br>Ajouter une clé d\'Equipe : <form style="display: inline-block;" method="post" action="scripts/login.php"><input type="text" name="team_key_login" id="team_key_login" size="15" placeholder="TM-XXXX / AD-XXXX" required></input><input type="submit" value="Connect"></form></span>',
"raw_sr_error_logged" => 'Vous n\'êtes pas autorisé à accéder à ce rapport.<br><br><span class="status_positif">Vous êtes déjà connecté à une Equipe.</span><br><br>',
"raw_sr_error_logged2" => '<span class="status_negatif">Aucune Equipe correspondante trouvée. Demandez la clé et ajoutez la : </span><br><form method="post" action="scripts/team_add.php"><input name="team_key_login" id="team_key_login" size="20" placeholder="TM-XXXX-XXXX-XXXX-XXXX" required></input><input type="submit" value="Ajouter une Equipe"></form><br><br>',
"raw_sr_error_logged3" => '<span class="status_positif">Vous pouvez gérer vos Equipes depuis le menu <a href="/?page=team#multi-team">Multi-Team management</a>.</span>',
"discord_private_sr_error_swap_display" => 'Afficher le RE en se connectant à l\'Equipe ',
"discord_private_sr_error_swap" => 'Se connecter à l\'Equipe ',
"discord_cant_find_sr" => "Cant find this spy report",
"alias_link_before" => "Profil de ",
"alias_link_after" => "",
"alias_link_tooltip" => "Alias du joueur sur le PTRE",
"expedetector_link_before" => "Profil d'expéditions de ",
"expedetector_link_after" => "",
"team_no_discord_server" => "Aucun serveur Discord n\'est associé à votre équipe !",
"team_no_discord_server_not_admin" => "Demander à un Admin (le créateur de votre équipe, par exemple) de le faire.",
"team_key_swaped" => 'Vous êtes connecté à l\'Equipe ',
"team_key_added" => "Clé ajoutée. Bienvenue !",
"team_key_added_suite" => "<br><br>Univers sélectionné : ",
"team_key_added_no_uni" => '<br><br>Pas d\'univers sélectionné',
"team_key_added_home_link" => "Voir les derniers rapports",
"team_creation_failed_size" => "Impossible de créer cette équipe : 2 caratères minimum",
"team_creation_already_exists" => "Impossible de créer cette équipe : ce nom d'équipe existe déjà",
"team_creation_already_created" => "Impossible. Vous avez déjà créé 5 équipes. Demander une création manuelle sur Discord.",
"team_creation_ok" => "Team créée !<br><br>Attention à bien conserver la clé ADMIN dans un document externe : ",
"multi_team_key_already_exists" => "Cette clé a déjà été ajoutée.<br>Vous pouvez basculer vers cette équipe via le menu Multi-Teams ci-dessous.",
"multi_team_key_key_added" => "Cette clé a été ajoutée.<br>Vous pouvez basculer vers cette équipe via le menu Multi-Teams ci-dessous.",
"multi_team_max_nb_keys" => 'Erreur : Impossible d\'ajouter plus de 5 équipes.',
"easy_ag_simulator_no_sim" => 'Erreur : Pas de simulation en cours.<br><a href="/?page=easy_ag_simulator">Ouvrir Easy AG simulator pour commencer</a>.',
"key_removed" => "Clé supprimée",
"search_error_min" => "ERREUR : La recherche doit contenir au moins 3 caratères",
"main_title" => "Les 10 derniers rapports (flottes)",
"main_intro_1" => ' rapports d\'espionnages pour cet univers',
"main_intro_2" => ' rapports d\'espionnages privés',
"player_list_color_1" => "< 1 semaine",
"player_list_color_2" => "< 1 mois",
"player_list_color_3" => "> 1 mois",
"player_acti_color_1" => "< 1 heure",
"player_acti_color_2" => "< 1 jour",
"player_acti_color_3" => "> 1 jour",
"display_report" => "Voir le rapport",
"spy_report_added" => "RE ajouté !",
"spy_report_added_error" => "Impossible de trouver le rapport : ",
"spy_report_added_exists" => "Ce RE existe déjà !",
"class_label" => "Classe : ",
"collector" => "Collecteur",
"general" => "Général",
"discoverer" => "Explorateur",
"no_class" => "pas de classe",
"collector_mini" => "[C]",
"general_mini" => "[G]",
"discoverer_mini" => "[E]",
"no_class_mini" => "[?]",
"activity_label" => "Activité : ",
"profile_label" => "Profil PTRE",
"spy_label" => "Espion : ",
"activity_raw_data" => "Table d'Activités Ingame",
"activity_graph_label" => "Graphique d'activité Ingame",
"last_gala_event" => "Derniers évènements de la galaxie",
"last_spy" => "Derniers Espions",
"activity_graph_intro" => 'Afin d\'alimenter le graphique d\'activités IG, vous devez installer <a href="https://openuserjs.org/scripts/nullNaN/OGLight" target="_blank">OGLight</a> / Infinity / <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a> et ajouter votre clé d\'Equipe dans les paramètres OGL.<br>Puis, vous devrez épingler la cible et régulièrement parcourir ses positions via le menu de droite.<br>',
"activity_graph_intro2" => '<b>Ci-dessous, vous pouvez consulter les dernières entrées<br>afin de vous aussurer que le push d\'activité fonctionne.</b><br><br><table><tr><td align="right"><span class="status_positif">(COA)</span> : </td><td>indique une activité provenant d\'une Equipe de votre Coalition.</td></tr><tr><td align="right"><span class="status_warning">(SpyMess)</span> : </td><td>indique un sondage de la part du joueur en question.</td></tr></table><br>',
"activity_graph_intro3" => 'Ici, vous pouvez choisir les options d\'affichage du graphique.<br><br>',
"activity_graph_not_available" => 'Pas assez de données d\'activité afin de générer les graphiques.<br><br>Vous devez installer <a href="https://openuserjs.org/scripts/nullNaN/OGLight" target="_blank">OGLight</a> / Infinity / <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a>, épingler la cible et régulièrement parcourir ses positions afin d\'envoyer les données d\'activités.',
"activity_oglight_data_not_available" => 'Pas assez de données OGLight. Vous devez installer <a href="https://openuserjs.org/scripts/nullNaN/OGLight" target="_blank">OGLight</a> / Infinity / <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a>.',
"activity_graph_not_connected" => 'Vous devez être connecté afin de consulter les graphiques d\'activités.',
"activity_recent_galaxy_update_warning" => 'Les données publiques de la galaxie ont été mises à jour récemment, il y a donc peu d\'évènements à afficher.<br>Revenez demain.',
"migration_add_sr" => "RE ajouté à la liste de migration : ",
"migration_add_failed" => 'Impossible d\'ajouter ce RE à la liste de migration : migrer ceux déjà selectionnés',
"migration_title" => "Migration de RE",
"migration_link" => "Migrer ce RE vers un autre univers",
"migration_available" => "Univers disponibles : ",
"migration_text" => 'Vous pouvez sélectionner jusqu\'à 10 RE à migrer (en même temps) vers le même univers.<br>L\'univers cible doit au moins contenir un RE de votre équipe.',
"sr_migrated_label" => "RE migré",
"player_profil_not_found" => '<span class="status_negatif large_text">Impossible de trouver des rapports d\'espionnages liés à ce joueur.</span><br><br>',
"player_profil_not_found_logged" => 'Assurez-vous d\'être connecté à la bonne Equipe :<br><br>',
"player_profil_not_found_not_logged" => 'Vous n\'êtes pas connecté à une Equipe.<br><br><a href="/?page=team">Veuiller vous connecter</a> via une clé d\'Equipe.</a>',
"player_profil_not_found_swap_team" => 'Se connecter à l\'Equipe ',
"carto_player_not_found" => 'Impossible de trouver ce joueur dans l\'API. Peut-être qu\'il n\'existe plus ?',
"report_player_into" => 'Si vous êtes sur de vous, vous pouvez signaler et supprimer tous ses rapports : ',
"report_player_tooltip" => "Attention",
"report_player_link" => "Signaler et supprimer tous les rapports de ce joueur",
"report_all_player_ok" => "Tous les rapports de ce joueur ont été signalés.",
"report_universe" => "RE signalés : ",
"cartography_title" => "Cartographie",
"stats_status_re" => "<b>Rapports d'espionnage</b><br><i>Discord + tools ingame</i>",
"stats_status_re_ogl" => '<b>Rapports d\'espionnage</b><br>Depuis Discord<br><span class="status_positif">Depuis OGLight</span><br><span class="status_negatif">Depuis Infinity</span><br><span class="status_warning">Depuis <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a> pour AGR</span><br>Depuis le site',
"stats_status_teams_actives" => "<b>Equipes actives - Site Web</b>",
"stats_status_discord" => "<b>Equipes actives - Discord</b>",
"stats_status_nb_acti_pushed" => '<b>Activités ingame</b><br><span class="status_positif">Depuis OGLight</span><br><span class="status_negatif">Depuis Infinity</span><br><span class="status_warning">Depuis EasyPTRE</span>',
"stats_status_nb_ogl_requests" => '<b>Requètes de profil</b><br><span class="status_positif">Depuis OGLight</span><br><span class="status_negatif">Depuis Infinity</span><br><span class="status_warning">Depuis EasyPTRE</span>',
"stats_status_nb_grap" => "<b>Graphiques d'activités consultés</b><br><i>Sur le site, uniquement</i>",
"stats_status_nb_planets" => "<b>Evènements de galaxie</b>",
"more_statistics" => "Plus de statistiques",
"ptre_statistics" => "STATISTIQUES",
"easy_ag_simulator_intro" => "<b>Comment ça marche ?</b><br><br>
        <ul>
            <li>Préambule : il faut que toutes les <b>flottes concernées soient disponibles sur le site PTRE</b>. Si ce n'est pas le cas, vous pouvez ajouter les API dans le formulaire au dessus. (Rappel : tous les RE ajoutés <b>sans être connecté</b> à une équipe seront <b>publics</b>.)</li>
            <li>Appuyer sur le lien <b>\"Add a fleet\"</b> puis parcourez le site à la recherche des flottes concernées</li>
            <li>Une fois sur un RE à ajouter, sélectionnez <b>\"Ajouter en tant qu'attaquant\"</b> ou <b>\"Ajouter en tant que défenseur\"</b> afin d'ajouter ce RE</li>
            <li>Répéter cette opération jusqu'à ce que votre AG soit complète</li>
            <li>Sélectionner les <b>options de simulations</b>, puis <b>valider</b> !</li>
        </ul>",
"easy_ag_simulator_no_tech" => "Pas de tech",
"easy_ag_simulator_cdr" => "Pourcentage CDR (temporaire) /!\\",
"easy_ag_simulator_degrouper" => "Dégrouper les flottes attaquantes",
"easy_ag_simulator_divide" => "Diviser les flottes et défenses par 10",
"easy_ag_simulator_rip" => "Supprimer les EDLM attaquantes",
"easy_ag_simulator_gt" => "Supprimer les GT attaquants",
"easy_ag_simulator_rec" => "Supprimer les recycleurs attaquants",
"easy_ag_simulator_probe" => "Supprimer les sondes attaquantes",
"easy_ag_simulator_vc" => "Supprimer les VC attaquants",
"easy_ag_simulator_sim_count" => "Nombre de simulations",
"easy_ag_simulator_attaquant" => "Attaquant(s)",
"easy_ag_simulator_defenseur" => "Defenseur(s)",
"easy_ag_simulator_label" => 'EASY AG',
"public_spy_reports_label" => 'RE PUBLICS',
"main_title_public_sr" => 'Derniers Rapports d\'Espionnages Publics',
"main_title_public_sr_top" => 'Top 100 des flottes publiques',
"main_title_public_sr_add_sr" => 'Ajouter un Rapport d\'Espionnage Public',
"public_sr_add_sr_warning" => '<span class="status_negatif large_text">Ajouter un RE dans le formulaire ci-dessous le rendra public, même si vous êtes connecté à votre équipe PTRE</span>',
"public_sr_add_sr_warning_connected" => '<span class="large_text">Utiliser le formulaire en haut à droite pour l\'ajouter à votre équipe PTRE</span>',
"welcome_back_message" => 'Bienvenue !<br><br>Vous pouvez <a href="https://discord.gg/EkYerfX9Xu" target="_blank">rejoindre le Discord PTRE</a> afin de suivre les dernières actualités,<br>proposer des idées, obtenir de l\'aide, etc...',
"options_page_intro" => 'Ajouter vos technos afin de directement les envoyer au simulateur. Il faut remplir tous les champs afin que ça soit prit en compte dans le simulateur.<br><br>Vous pouvez définir une configuration de technologies par univers.',
"options_page_tech_fight_title" => 'Technologies de combat',
"options_page_tech_speed_title" => 'Technologies Vitesses',
"options_page_tech_cargo_title" => 'Technologie Fret',
"options_page_speed" => 'Vitesse univers',
"options_page_speed_comment" => 'Mettre "1" par défaut.',
"gee_presentation" => '<span class="medium_text">Le Galaxy Event Explorer affiche la galaxie en combinant les données de :
                               <br>- L\'API publique, mise à jour une fois par semaine (comme sur MMORPG)
                               <br><span class="status_posifit">- PLUS tous les données que votre équipe a collectées depuis la dernère mise à jour</span>
                               <br><br>Pour collecter les données ingame, vous devez installer <a href="https://openuserjs.org/scripts/nullNaN/OGLight" target="_blank">OGLight</a> / <a href="https://ogameinfinity.com/" target="_blank">Infinity</a> / <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a></span>',
"gee_punchline" => '<span class="medium_text">Observer la galaxy telle qu\'ingame</span>',
"gee_public_user_warning" => 'Vous devez être connecté à votre équipe pour voir les évènements live ingame',
"gee_pos_count" => ' nouvelles positions ont été importées par OGLight / Infinity / EasyPTRE depuis la dernière MAJ de l\'API',
"p8_punchline" => '<span class="medium_text">Vos P8 en un seul click !</span>',
"p8_presentation" => '<span class="medium_text">Utiliser le tableau ci-dessous afin de choisir la position que vous rechercher (P1, P8, P15 ?).<br>Ensuite, vous pouvez visualiser le contenu du système solaire.<br>Si vous êtes connectés à votre Equipe PTRE, la galaxie tiendra compte des pushs de positions ingame depuis OGL/OGI/EasyPTRE.</span>',
"ss_finder_punchline" => '<span class="medium_text">Vos systèmes safes en un click !</span>',
"ss_finder_presentation" => '<span class="medium_text">Cet outils permet de lister les systèmes solaires vides, en se basant sur l\'API publique, mais aussi de vos données envoyées depuis ingame.<br>Si vous êtes connectés à votre Equipe PTRE, la galaxie tiendra compte des pushs de positions ingame depuis OGL/OGI/EasyPTRE.</span>',
"messages_intro" => 'Tous les nouveaux messages seront supprimés 24 heures après leur lecture.',
"messages_user_comment" => 'Ces messages vous concernent',
"messages_admin_comment" => 'Ces messages concernent votre équipe',
"menu_link_discord" => "DISCORD SETUP",
"menu_link_search" => "RECHERCHE",
"menu_link_options" => "OPTIONS",
"menu_link_lifeform_researchs" => "TECHNOS",
"no_universe_selected" => "Pas d'univers sélectionné",
"comparator_title" => "Comparateur de flottes et technos",
"comparator_display" => "Afficher le comparateur de flottes et technos",
"comparator_add_button" => "AJOUTER LA FLOTTE AU COMPARATEUR",
"comparator_purge_label" => "Purger toutes les flottes",
"comparator_description" => '<span class="medium_text"><hr><br>Aucune flotte ajoutée au comparateur...<br><br>Pour ajouter des flottes, consulter un rapport et utiliser le bouton "AJOUTER LA FLOTTE AU COMPARATEUR".<br><br><img src="/img/ptre_fleet_comparator.png"></span>',
"profile_quick_menu" => '<a href="#anchor_fleet">FLOTTE / CARTO</a> | <a href="#anchor_researchs">TECHNOS</a> | <a href="#anchor_lfresearchs">TECHNOS FDV</a> | <a href="#anchor_events">EVENEMENTS IG</a> | <a href="#anchor_actitable">TABLE ACTIVITE</a> | <a href="#anchor_actigraph">GRAPHIQUE</a> | <a href="#anchor_sr">ESPIONNAGES</a>',
"lifeforms_page_title" => 'VOS TECHNOS DE FORMES DE VIES',
"easyptre_notification" => '<span class="status_warning small_text">EasyPTRE n\'est pas installé !</span><br><span class="status_positif small_text">EasyPTRE apporte de nouvelles fonctionnalités<br>et est entièrement compatible avec AGR/OGL/OGI</span><br><a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">Installation</a>',
"options_install_easyptre" => '<table><tr><td align="center" align="top"><span class="medium_text"><h3>Synchronisation des Tech Formes de Vies</h3><br>Bonjour explorateur !<br><br>T\'en as marre d\'entrer tes technos Formes de vies à la main dans les simulateurs ? N\'en dis pas plus !<br>Cette fonctionnalité est faite pour toi et va te faire gagner du temps.
                             <br><br><span class="status_warning">Il te suffit d\'installer <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">EasyPTRE</a> afin de synchroniser tes techs FDV.</span><br>Une fois fait, tous les RE PTRE contiendront tes techonologies préremplies pour les simulateurs.
                             <br><br>Depuis la sortie d\'EasyPTRE 0.9, l\'outil n\'est plus limité aux seuls utilisateurs d\'AGR.<br>Les utilisateurs d\'OGLight et OGinfinity n\'ont pas à changer leurs habitudes:<br>EasyPTRE gerera seulement certaines tâches (FDV) tout en laissant votre outil préféré faire le reste.
                             <br><br><hr><br><h3>Installation</h3><br>- <a href="https://www.tampermonkey.net/" target="_blank">Installer Tampermonkey</a><br>- <a href="https://openuserjs.org/scripts/GeGe_GM/EasyPTRE" target="_blank">Installer EasyPTRE</a><br>- Parcourir la page flotte, qui sauvera vos technologies<br>- Revenez ici, ce message devrait avoir disparu !</span></td><td align="center"><img src="/img/ptre_lifeforms.png"></td></tr></table>'
];


?>
